scenario: 'main-synthetic' 
num-instruments: 1
num-treatments: 1
direct-riesz: False
true-theta-num-sample: 100000000
num-reps: 100
setup-options:
  clever:
    - True
  dgp-version: 
    - 'abs'
    - '2dpoly'
    - 'sigmoid'
    - 'sin'
  n:
    - 500
    - 1000
    - 2000
  iv-strength:
    - 0.2
    - 0.5
model-kwargs:
  p_dropout: 0.1
  n_hidden: 100
learner-kwargs:
  learner_lr: !!float 5e-3
  adversary_lr: !!float 5e-2
  learner_l2: !!float 1e-6
  adversary_l2: !!float 1e-6
  n_epochs: 10000
  bs: 100
  min_eval_epoch: 50
  n_earlystop_funcs: 1000
  earlystop_save_every: 5
q-reg-kwargs:
  min_samples_leaf: 20
base_lambda_l2_h: !!float 1e-3
# learner-kwargs:
#   learner_lr: !!float 1e-4
#   adversary_lr: !!float 1e-4
#   learner_l2: !!float 1e-3
#   adversary_l2: !!float 1e-3
#   n_epochs: 2000
#   bs: 100
#   min_eval_epoch: 50
# q-reg-kwargs:
#   min_samples_leaf: 20